# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72f91493a0890d27084240b239756d85d08144cbcfb3937b0b35b10020fc7a7fa7a1bdd05faf16ad0a57c094ab57be916788701482e4136538362a0c066d4063

test:
  secret_key_base: 8d86b7ff6d5560532c2daa6085795aec633a25b43066679dfc34a3c5d7272296b02684181c8bccac7d563eff68bfd680c6ac080af9f55073544b20d73f8ad5a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
